-- Bring the existing database up to the current Prisma schema.

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "isSuspended" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Student"
ADD COLUMN IF NOT EXISTS "board" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "area" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "timing" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "guardianName" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "guardianPhone" TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS "notes" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Student"
ALTER COLUMN "name" SET DEFAULT '',
ALTER COLUMN "class" SET DEFAULT '',
ALTER COLUMN "subjects" SET DEFAULT '',
ALTER COLUMN "address" SET DEFAULT '',
ALTER COLUMN "city" SET DEFAULT '',
ALTER COLUMN "pincode" SET DEFAULT '',
ALTER COLUMN "contactNumber" SET DEFAULT '';

ALTER TABLE "Teacher"
ADD COLUMN IF NOT EXISTS "monthlyFee" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Teacher"
ALTER COLUMN "name" SET DEFAULT '',
ALTER COLUMN "qualification" SET DEFAULT '',
ALTER COLUMN "experience" SET DEFAULT 0,
ALTER COLUMN "subjects" SET DEFAULT '',
ALTER COLUMN "location" SET DEFAULT '',
ALTER COLUMN "city" SET DEFAULT '',
ALTER COLUMN "pincode" SET DEFAULT '';

CREATE TABLE IF NOT EXISTS "CoinPackage" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "coins" INTEGER NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CoinPackage_pkey" PRIMARY KEY ("id")
);
